### ISSUE TITLE
The main xi-cam window does not appear after the initial start-up window with x--cam logo on it

### ISSUE THREAD

**Issue by sxr95** [ronpandolfi/Xi-cam#30]
The initial xi-cam logo starts after I run xi-cam from pycharm but the main xi-cam window does not start after the initial xi-cam logo disappears

**Comment by ronpandolfi** [comment]
Please look for the crash log in your user/home directory named `err.log` and `out.log`, and share them here.

**Comment by sxr95** [comment]
[out.log](https://github.com/ronpandolfi/Xi-cam/files/1749345/out.log)

My err file is empty. Above is the out file.

**Comment by ercius** [comment]
This is still an issue. I can not get xicam to start up on Windows 10 Pro using a fresh anaconda environment of Python 3.6.

I tried two ways to start the program
1) Activate the anaconda environment. Type in xicam and press enter. The splash screen shows up and then stays there indefinitely. There are no error messages printed to the console. I can not remove the splash screen until I reboot my computer
2) In site-packages\xicam there is a file called run_xicam.py. This has the same effect as 1 but there are error messages printed to the console. The first error message for venvs.py indicates os.sync() does not exist. I commented out this line and then it complains about the default virtual environment not existing.

Is there a preferred way to start the program? I did not see anything in the readme beyond installation using pip.

**Comment by ronpandolfi** [comment]
Hi Peter, by your description, it sounds like you have installed Xi-cam 2 (see https://github.com/lbl-camera/Xi-cam). To install Xi-cam 1, you must pin the version when installing from pip (`pip install xicam==1.2.18`).

There have been some issues related to Xi-cam 2's sandbox-ing of plugins into a virtualenv. I've opened other issues to track the progress: 
https://github.com/lbl-camera/Xi-cam/issues/1
https://github.com/lbl-camera/Xi-cam/issues/2

The issue described in your (2) is also one that has already been addressed, but the changes had not yet been packaged into the pip release. I have pushed an updated release to pip that should solve your issue. Note: the 'xicam' entry point does not currently work on windows; you must use the run_xicam.py script.

**Comment by ercius** [comment]
Thanks for the quick response! I bet you are right. I did not think to check the version number of xicam installed. Ill try out v 1.2.18. Thanks for the information on using run_xicam.py as well. Looking forward to trying out the software! The demos looked very impressive.
